### PR TITLE
Proofread for grammar, clarity, style

### PR DESCRIPTION
**Pull request by pdaian**
Native English speaker, quick proofread for substantial grammar/clarity improvements.

Also correct some incorrect math - nodes processing P2P network data at twice incoming speed means it would take them the amount of downtime to correct, not half the amount of downtime (equations for this were provided to @zander).

**Public Disclaimer**: My proofreading of this post does not imply that I agree with or endorse its content or conclusions, and simply represents an effort to improve the clarity and fidelity of the debate.  The post was proofread for style and clarity only, not content.  For example, I think the effects of P2P relaying are not fully considered here, and an analysis of the operation of the network in adverse conditions or under degraded transport service is also missing.  I find the high scaling numbers dubious, though I think it is clear that bandwidth, disk space, and sync time are surmountable problems.  I do believe the network calls for and requires much more than a 2x differential between processing speed and relay speed, with a 5x+ differential likely being ideal for nodes to be able to resync after downtime and robustly handle degraded service.  More simulations with the deployed versions of the software are required to reach final conclusions.

### CODE REVIEW

**Comment by zander** [comment]
Wow, I'm actually a little embarrassed by the amount of issues you had to correct.

Thanks a lot of that!

**Comment by pdaian** [comment]
Don't be embarrassed, a lot of them were personal preference.  And being a super nitpicky proofreader comes with the grad student territory :).  It was actually quite good for a non-native speaker, definitely better than anything I'd do in (I'm guessing?) German :+1:.

Cheers!

**Comment by zander** [comment]
>  I do believe the network calls for and requires much more than a 2x differential between processing speed and relay speed, with a 5x+ differential likely being ideal for nodes to be able to resync after downtime and robustly handle degraded service. More simulations with the deployed versions of the software are required to reach final conclusions.

The 2-times is indeed not really good enough for initial sync. I fully agree.  I guess I could change it since the current hardware can handle that trivially already.

The network is a different issue, and it depends a lot on what kind of requirements the people have. Personally I live in a country where I already have 5x with no issues. And we don't even have fiber based internet.

**Comment by pdaian** [comment]
I think the best next step we can take as a community towards ending the scaling debate is to create a sandbox where people can run forks with whatever blocksizes or consensus modifications they want, populate these sandboxes with real nodes running on varying hardware levels across the world, and gather massive amounts of data from each individual node.  We also have to consider propagation latency in these analyses, which such tests would help us do.  A simulation of that is "next best" and perhaps easier to achieve, but it's hard to argue with concrete data.


I agree with you on the network angle; my gut feeling from the analyses I've seen is that we'll run into software bottlenecks far before we run into network bottlenecks on competently peered and spec'd networks.  I just don't see a gigabit fiber line having problems with even up to 100MB+ blocks.  These software bottlenecks would then be addressable with software changes, that would be testable in the sandbox.

There could even be a simulated exchange allowing for users to trade coins across chains, establishing which chains have market dominance in the experiment and making a market case for a switch.

**Comment by zander** [comment]
I've been thinking about how to make such a system. First thing was to have a better RPC interface (a webserver is just not useful) so a remote user can subscribe to log-lines and things like "block x came in at time y" can be monitored.

I started working on that, but got distracted because there were more pressing matters.

Before such a system is in place I don't see how we can do proper bigger network deployments.

**Pull request merged**
